#!/bin/bash

/usr/bin/wait_on_postgres.py

#TODO: Determine list of installed plugins by inspecting image contents
scl enable rh-python36 "django-admin migrate --noinput"
scl enable rh-python36 "django-admin migrate auth --noinput"

exec scl enable rh-python36 "gunicorn -b 0.0.0.0:24817 pulpcore.app.wsgi:application"
